name: Livewire
favicon: null
layout_spectrum: 0.46820703288540244
typography_spectrum: 0.7661297188606113
title: IoT Consultants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4263806766830385
  lightness: 0.7762335422448814
  saturation: 0.5416471068747342
  rhythmicContrast: 0.005030285334214568
purpose: []
